<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['app123'] = array(
    array(
        'type'=>'平台',
        'icon'=>'icon-dotA2.png',
        'items'=>array(
            array(
                'name'=>'Email',
                'link'=>'http://mail.test.com/',
                'icon'=>'icon-gmail.png',
            ),
            array(
                'name'=>'Wiki',
                'link'=>'http://wiki.test.com/',
                'icon'=>'icon-wiki.png',
            ),
            array(
                'name'=>'JIRA',
                'link'=>'http://jira.test.com/',
                'icon'=>'icon-wiki.png',
            ),
            array(
                'name'=>'Git',
                'link'=>'http://git.test.com/',
                'icon'=>'icon-git.png',
            ),
        ),
    ),
    array(
        'type'=>'监控平台',
        'icon'=>'icon-dotA2.png',
        'items'=>array(
            array(
                'name'=>'Falcon',
                'link'=>'http://dashboard.test.com/',
                'icon'=>'icon-falcon.png',
            ),
            array(
                'name'=>'Urlooker',
                'link'=>'http://urlooker.test.com/',
                'icon'=>'icon-urlooker.png',
            ),
        ),
    ),
    array(
        'type'=>'运维平台',
        'icon'=>'icon-dotA2.png',
        'items'=>array(
            array(
                'name'=>'DNSPod',
                'link'=>'https://www.dnspod.cn/',
                'icon'=>'icon-dnspod.jpg',
            ),
            array(
                'name'=>'阿里云',
                'link'=>'https://www.aliyun.com/',
                'icon'=>'icon-aliyun.png',
            ),
            array(
                'name'=>'Jenkins',
                'link'=>'http://jenkins.test.com/',
                'icon'=>'icon-jenkins.png',
            ),
            array(
                'name'=>'Zipkin',
                'link'=>'http://zipkin.test.com/',
                'icon'=>'icon-zipkin.png',
            ),
            array(
                'name'=>'Kubernetes',
                'link'=>'http://k8s.test.com/',
                'icon'=>'icon-k8s.png',
            ),
        ),
    ),
    array(
        'type'=>'消息队列',
        'icon'=>'icon-dotA2.png',
        'items'=>array(
            array(
                'name'=>'RabbitMQ',
                'link'=>'http://rabbitmq.test.com/',
                'icon'=>'icon-rabbitmq.png',
            ),
            array(
                'name'=>'ActiveMQ',
                'link'=>'http://activemq.test.com/admin/queues.jsp',
                'icon'=>'icon-activemq.jpg',
            ),
        ),
    ),
    array(
        'type'=>'大数据',
        'icon'=>'icon-dotA2.png',
        'items'=>array(
            array(
                'name'=>'Zookeeper',
                'link'=>'http://zookeeper.test.com/',
                'icon'=>'icon-zkui.png',
            ),
            array(
                'name'=>'Kafka',
                'link'=>'http://kafka.test.com/',
                'icon'=>'icon-kafka.png',
            ),
            array(
                'name'=>'Azkaban',
                'link'=>'http://azkaban.test.com/index',
                'icon'=>'icon-azkaban.png',
            ),
            array(
                'name'=>'Hadoop',
                'link'=>'http://hadoop.test.com',
                'icon'=>'icon-hadoop.png',
            ),
            array(
                'name'=>'Kylin',
                'link'=>'http://kylin.test.com/kylin',
                'icon'=>'icon-kylin.png',
            ),
            array(
                'name'=>'Hbase',
                'link'=>'http://hbase.test.com',
                'icon'=>'icon-hbase.png',
            ),
            array(
                'name'=>'Storm',
                'link'=>'http://storm.test.com/',
                'icon'=>'icon-storm.png',
            ),
            array(
                'name'=>'Spark',
                'link'=>'http://spark.test.com/',
                'icon'=>'icon-spark.png',
            ),
        ),
    ),
);

