CREATE DATABASE IF NOT EXISTS sre;

USE sre;

CREATE TABLE IF NOT EXISTS duty (
    id BIGINT NOT NULL AUTO_INCREMENT,
    team VARCHAR(256) NOT NULL DEFAULT 'sre',
    duty_date DATE NOT NULL DEFAULT '2017-05-01',
    op VARCHAR(256) NOT NULL DEFAULT 'zhangsan',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Duty';
