CREATE DATABASE IF NOT EXISTS sre;

USE sre;

CREATE TABLE IF NOT EXISTS event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(1024) NOT NULL,
    url VARCHAR(1024) NOT NULL DEFAULT 'https://www.baidu.com/',
    class VARCHAR(32) NOT NULL DEFAULT 'event-info',
    `start` VARCHAR(16) NOT NULL DEFAULT '1493863200000',
    `end` VARCHAR(16) NOT NULL DEFAULT '1493866800000',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Event';
