CREATE DATABASE IF NOT EXISTS sre;

USE sre;

CREATE TABLE host (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hostname VARCHAR(256) NOT NULL,
    ip VARCHAR(64) NOT NULL DEFAULT '127.0.0.1',
    idc BIGINT NOT NULL,
    cpu VARCHAR(512) NOT NULL DEFAULT '',
    memory VARCHAR(512) NOT NULL DEFAULT '',
    disk VARCHAR(512) NOT NULL DEFAULT '',
    ssd VARCHAR(512) NOT NULL DEFAULT '',
    raid VARCHAR(512) NOT NULL DEFAULT '',
    nic VARCHAR(512) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Host';
