CREATE DATABASE IF NOT EXISTS sre;

USE sre;

CREATE TABLE IF NOT EXISTS idc (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    address VARCHAR(256) NOT NULL DEFAULT '',
    administrator VARCHAR(256) NOT NULL DEFAULT '',
    tel VARCHAR(256) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='IDC';
