<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['billboard'] = array(
        array(
            'type'=>'运维平台',
            'icon'=>'icon-dotA2.png',
            'items'=>array(
                array(
                    'name'=>'Gitlab',
                    'link'=>'',
                    'icon'=>'icon-dotA2.png',
                ),
                array(
                    'name'=>'Jenkins',
                    'link'=>'',
                    'icon'=>'icon-dotA2.png',
                ),
                array(
                    'name'=>'Kubernete',
                    'link'=>'',
                    'icon'=>'icon-dotA2.png',
                ),
            ),
        ),
        array(
            'type'=>'监控平台',
            'icon'=>'icon-dotA2.png',
            'items'=>array(
                array(
                    'name'=>'FE',
                    'link'=>'',
                ),
                array(
                    'name'=>'Portal',
                    'link'=>'',
                ),
                array(
                    'name'=>'Dashboard',
                    'link'=>'',
                ),
                array(
                    'name'=>'Issues',
                    'link'=>'',
                ),
            ),
        ),
        array(
            'type'=>'大数据平台',
            'icon'=>'icon-dotA2.png',
            'items'=>array(
                array(
                    'name'=>'Hadoop-Jobtracker',
                    'link'=>'',
                ),
                array(
                    'name'=>'Hadoop-Datanode',
                    'link'=>'',
                ),
                array(
                    'name'=>'Hbase',
                    'link'=>'',
                ),
                array(
                    'name'=>'Hive',
                    'link'=>'',
                ),
                array(
                    'name'=>'Spark',
                    'link'=>'',
                ),
                array(
                    'name'=>'Kafka',
                    'link'=>'',
                ),
                array(
                    'name'=>'ZooKeeper',
                    'link'=>'',
                ),
            ),
        ),
    );

/* End of file app_billboard.php */
/* Location: ./application/config/app_billboard.php */
